### Base de Dados importada ‚û° https://www.kaggle.com/datasets/utkarshx27/movies-dataset
### Problema ‚û° Limpar Base de Dados e Trazer informa√ß√µes necess√°rias
### Solu√ß√£o abaixo üëáüèº

In [5]:
import pandas as pd

table_filmes = pd.read_csv("movie_dataset.csv")
display(table_filmes)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond‚Äôs past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

### Tratando e Analisando Valores Nulos

In [12]:
table_filmes['genres'] = table_filmes['genres'].fillna('without genres')

table_filmes['homepage'] = table_filmes['homepage'].fillna('no home page')

table_filmes['keywords'] = table_filmes['keywords'].fillna('no keywords')

table_filmes['tagline'] = table_filmes['tagline'].fillna('no tagline')

display(table_filmes)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond‚Äôs past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,4798,220000,Action Crime Thriller,no home page,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,no home page,72766,no keywords,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,no tagline,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,without genres,http://shanghaicalling.com/,126186,no keywords,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,no home page,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,no tagline,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

### Tratando e Analisando a quantidade de filmes por gen√™ros

In [24]:
qnt_filmes_genero = table_filmes['genres'].value_counts()
display(qnt_filmes_genero)

Drama                                                370
Comedy                                               282
Drama Romance                                        164
Comedy Romance                                       144
Comedy Drama                                         142
                                                    ...
Action Comedy Family Adventure                         1
Drama Adventure Western                                1
Adventure Fantasy Action Romance                       1
Fantasy Action Adventure Science Fiction Thriller      1
Comedy Drama Romance TV Movie                          1
Name: genres, Length: 1169, dtype: int64

### Tratando e Analisando o or√ßamento por categoria

In [31]:
orcamento_genero = table_filmes[['budget', 'genres']].groupby(['genres']).sum()
display(orcamento_genero)

                                                      budget
genres
Action                                             834000000
Action Adventure                                   819200000
Action Adventure Animation Comedy Family           246000000
Action Adventure Animation Comedy Science Fiction          0
Action Adventure Animation Family                   92000000
...                                                      ...
Western Drama                                       27000000
Western Drama Adventure Thriller                   135000000
Western History                                     10000000
Western History War                                145000000
without genres                                       3700001

[1169 rows x 1 columns]

### An√°lisando e Tratando A soma dos Votos e M√©dia por Gen√™ro/Filme

In [47]:
votos_total_media = table_filmes[['genres', 'title', 'vote_average', 'vote_count']].groupby(['genres', 'title']).sum()
display(votos_total_media)

                                                                vote_average  \
genres         title
Action         Agent Cody Banks                                          5.0
               Alatriste                                                 5.6
               American Heist                                            4.3
               Bloodsport                                                6.6
               Criminal                                                  5.7
...                                                                      ...
without genres The Book of Mormon Movie, Volume 1: The Journey           5.0
               The Little Ponderosa Zoo                                  2.0
               The Looking Glass                                         7.0
               The Outrageous Sophie Tucker                              0.0
               UnDivided                                                 0.0

                                                                vote_count
genres         title
Action         Agent Cody Banks                                        284
               Alatriste                                                61
               American Heist                                          158
               Bloodsport                                              363
               Criminal                                                557
...                                                                    ...
without genres The Book of Mormon Movie, Volume 1: The Journey           2
               The Little Ponderosa Zoo                                  1
               The Looking Glass                                         1
               The Outrageous Sophie Tucker                              0
               UnDivided                                                 0

[4802 rows x 2 columns]

### Analisando e Tratando Filmes com a Nota > 5

In [64]:
filmes_nota_maior_5 = table_filmes.loc[table_filmes['vote_average'] > 5.0, ['genres', 'title', 'vote_average']]
display(filmes_nota_maior_5)

,genres,title,vote_average
0,Action Adventure Fantasy Science Fiction,Avatar,7.2
1,Adventure Fantasy Action,Pirates of the Caribbean: At World's End,6.9
2,Action Adventure Crime,Spectre,6.3
3,Action Crime Drama Thriller,The Dark Knight Rises,7.6
4,Action Adventure Science Fiction,John Carter,6.1
...,...,...,...
4798,Action Crime Thriller,El Mariachi,6.6
4799,Comedy Romance,Newlyweds,5.9
4800,Comedy Drama Romance TV Movie,"Signed, Sealed, Delivered",7.0
4801,without genres,Shanghai Calling,5.7
4802,Documentary,My Date with Drew,6.3

### Analisando e Filmes com a Nota < 5

In [119]:
filmes_nota_menor_5 = table_filmes.loc[table_filmes['vote_average'] < 5.0, ['genres', 'title', 'vote_average']]
display(filmes_nota_menor_5)

,genres,title,vote_average
83,Action Adventure Science Fiction Romance,The Lovers,4.8
91,Action Adventure Science Fiction,Independence Day: Resurgence,4.9
138,Action Adventure Family Fantasy,The Last Airbender,4.7
162,Action,Stealth,4.9
210,Action Crime Fantasy,Batman & Robin,4.2
...,...,...,...
4783,Thriller Horror,Backmask,4.7
4785,Drama,Stories of Our Lives,0.0
4787,Science Fiction Thriller,All Superheroes Must Die,4.2
4791,Horror,Tin Can Man,2.0
4794,Thriller Horror Comedy,Sanctuary: Quite a Conundrum,0.0

In [117]:
maior_5 = 4189
menor_5 = 528
percentutal = (menor_5 / maior_5) * 100

print(percentutal)

12.604440200525186

### Resultado da An√°lise de Dados
- O gen√™ro com mais lan√ßamento de filmes √© o *Gen√™ro Drama*
- A categoria com or√ßamento mais alto √© a *Categoria Action*
- A diference na vota√ß√£o da m√©dia dos votos dos filmes com >5 ou com <5 √© equivalente √† 12% sob o total dos filmes